# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

title: HersonHN
author: Herson Salinas
theme: lugia

APP:
  production: https://www.herson.hn
  local: http://localhost:8000


url: https://herson.hn
root: /
permalink: :year/:title/

default_layout: index
external_link:
  enable: true
archive_dir: posts
tags_dir: tags

highlight:
  enable: true
  auto_detect: true
  line_number: false
  wrap: true

meta_generator: false
filename_case: 1
external_link.enable: true

feed:
  type: atom
  path: atom.xml
  limit: 20
  content: false
  order_by: -date
  autodiscovery: true


# compilation specifics
node_sass:
  outputStyle: compressed
  precision: 5
  sourceComments: false

skip_render:
  - assets/css/*
  - assets/js/*
  - assets/dist/*
  - assets/dist/**/*

exclude_generator:
  - index

## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
